import type { Metadata } from "next";
import { Bokor, Yrsa } from "next/font/google";
import "./globals.css";
import Header from "./layout/Header";
import Footer from "./layout/Footer";

const yrsa = Yrsa({
  variable: "--font-yrsa",
  subsets: ["latin"],
});

const bokorFont = Bokor({
  variable: "--font-bokor",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "EG Photography",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${yrsa.variable} antialiased`}>
        <Header />
        {children}
       
        <Footer />
      </body>
    </html>
  );
}
